# 파이썬 기초
## 3.라이브러리

### Pandas

- 데이터 불러와서 확인하기

---

In [1]:
import pandas as pd

In [2]:
from pandas import read_csv

In [3]:
# Google Drive를 마운트한다.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.csv', delimiter='|')

In [5]:
df.head()

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961   1            62.0          6.3         75.425       6.825
1  1961   2            83.2          7.2         75.425       6.825
2  1961   3            70.6          4.8         75.425       6.825
3  1961   4            85.9          9.0         75.425       6.825
4  1962   1            72.7          6.3         91.475       4.075

In [6]:
df.shape

(240, 6)

In [7]:
df.iloc[:,:]

        년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0    1961   1            62.0          6.3         75.425       6.825
1    1961   2            83.2          7.2         75.425       6.825
2    1961   3            70.6          4.8         75.425       6.825
3    1961   4            85.9          9.0         75.425       6.825
4    1962   1            72.7          6.3         91.475       4.075
..    ...  ..             ...          ...            ...         ...
235  2019   4        497064.8          2.3     479759.950       2.050
236  2020   1        458202.4         -1.3     478453.025      -0.300
237  2020   2        472328.1         -3.2     478453.025      -0.300
238  2020   3        491181.5          2.2     478453.025      -0.300
239  2020   4        492100.1          1.1     478453.025      -0.300

[240 rows x 6 columns]

In [8]:
df.iloc[:,0:3]

        년  분기  Nominal_GDP_분기
0    1961   1            62.0
1    1961   2            83.2
2    1961   3            70.6
3    1961   4            85.9
4    1962   1            72.7
..    ...  ..             ...
235  2019   4        497064.8
236  2020   1        458202.4
237  2020   2        472328.1
238  2020   3        491181.5
239  2020   4        492100.1

[240 rows x 3 columns]

In [9]:
df[['년','분기']]

        년  분기
0    1961   1
1    1961   2
2    1961   3
3    1961   4
4    1962   1
..    ...  ..
235  2019   4
236  2020   1
237  2020   2
238  2020   3
239  2020   4

[240 rows x 2 columns]

- 데이터 조건으로 확인하기

----

In [10]:
df[df['년']==1961]

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961   1            62.0          6.3         75.425       6.825
1  1961   2            83.2          7.2         75.425       6.825
2  1961   3            70.6          4.8         75.425       6.825
3  1961   4            85.9          9.0         75.425       6.825

In [11]:
df_1961 = df[df['년']==1961]
df_1962 = df[df['년']==1962]

- 데이터 붙이기

---

In [12]:
df_1961

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961   1            62.0          6.3         75.425       6.825
1  1961   2            83.2          7.2         75.425       6.825
2  1961   3            70.6          4.8         75.425       6.825
3  1961   4            85.9          9.0         75.425       6.825

In [13]:
df_1962

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
4  1962   1            72.7          6.3         91.475       4.075
5  1962   2            99.4         -1.6         91.475       4.075
6  1962   3            84.8          7.2         91.475       4.075
7  1962   4           109.0          4.4         91.475       4.075

In [14]:
df_1961 + df_1962

    년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0 NaN NaN             NaN          NaN            NaN         NaN
1 NaN NaN             NaN          NaN            NaN         NaN
2 NaN NaN             NaN          NaN            NaN         NaN
3 NaN NaN             NaN          NaN            NaN         NaN
4 NaN NaN             NaN          NaN            NaN         NaN
5 NaN NaN             NaN          NaN            NaN         NaN
6 NaN NaN             NaN          NaN            NaN         NaN
7 NaN NaN             NaN          NaN            NaN         NaN

In [15]:
pd.concat([df_1961, df_1962], axis=0)

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961   1            62.0          6.3         75.425       6.825
1  1961   2            83.2          7.2         75.425       6.825
2  1961   3            70.6          4.8         75.425       6.825
3  1961   4            85.9          9.0         75.425       6.825
4  1962   1            72.7          6.3         91.475       4.075
5  1962   2            99.4         -1.6         91.475       4.075
6  1962   3            84.8          7.2         91.475       4.075
7  1962   4           109.0          4.4         91.475       4.075

In [16]:
pd.concat([df_1961, df_1962], axis=1)

        년   분기  Nominal_GDP_분기  ...  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961.0  1.0            62.0  ...          NaN            NaN         NaN
1  1961.0  2.0            83.2  ...          NaN            NaN         NaN
2  1961.0  3.0            70.6  ...          NaN            NaN         NaN
3  1961.0  4.0            85.9  ...          NaN            NaN         NaN
4     NaN  NaN             NaN  ...          6.3         91.475       4.075
5     NaN  NaN             NaN  ...         -1.6         91.475       4.075
6     NaN  NaN             NaN  ...          7.2         91.475       4.075
7     NaN  NaN             NaN  ...          4.4         91.475       4.075

[8 rows x 12 columns]

- 데이터 Merge

---

In [17]:
left = df_1961[['년','분기','Nominal_GDP_분기','Real_GDP_분기']]
right = df_1961[['년','분기','Nominal_GDP_년','Real_GDP_년']]

In [18]:
pd.merge(left=left, right=right, left_on=['년', '분기'], right_on=['년', '분기'])

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961   1            62.0          6.3         75.425       6.825
1  1961   2            83.2          7.2         75.425       6.825
2  1961   3            70.6          4.8         75.425       6.825
3  1961   4            85.9          9.0         75.425       6.825

- 데이터 전처리 예제

---

In [19]:
import math

In [20]:
df['Nominal_GDP_년_applied'] = df.apply(lambda x:  math.floor(x.Nominal_GDP_년) if x.분기==1 else x.Nominal_GDP_년, axis=1)

In [21]:
df.head()

      년  분기  Nominal_GDP_분기  ...  Nominal_GDP_년  Real_GDP_년  Nominal_GDP_년_applied
0  1961   1            62.0  ...         75.425       6.825                 75.000
1  1961   2            83.2  ...         75.425       6.825                 75.425
2  1961   3            70.6  ...         75.425       6.825                 75.425
3  1961   4            85.9  ...         75.425       6.825                 75.425
4  1962   1            72.7  ...         91.475       4.075                 91.000

[5 rows x 7 columns]

In [22]:
df[df['분기']==1]

        년  분기  Nominal_GDP_분기  ...  Nominal_GDP_년  Real_GDP_년  Nominal_GDP_년_applied
0    1961   1            62.0  ...         75.425       6.825                   75.0
4    1962   1            72.7  ...         91.475       4.075                   91.0
8    1963   1            97.6  ...        129.625       9.100                  129.0
12   1964   1           128.5  ...        184.900       9.050                  184.0
16   1965   1           162.2  ...        207.825       7.750                  207.0
20   1966   1           198.1  ...        266.475      12.025                  266.0
24   1967   1           244.8  ...        328.450       9.250                  328.0
28   1968   1           330.9  ...        423.100      13.275                  423.0
32   1969   1           395.9  ...        552.850      14.200                  552.0
36   1970   1           536.9  ...        699.150      10.075                  699.0
40   1971   1           674.1  ...        859.525      10.875                  859.0
44   1972   1           804.7  ...       1066.925       7.025                 1066.0
48   1973   1          1039.8  ...       1381.850      14.850                 1381.0
52   1974   1          1545.6  ...       1976.250       9.925                 1976.0
56   1975   1          2007.6  ...       2635.900       7.500                 2635.0
60   1976   1          2806.7  ...       3618.200      13.225                 3618.0
64   1977   1          3569.8  ...       4652.025      12.000                 4652.0
68   1978   1          4813.0  ...       6288.600      11.375                 6288.0
72   1979   1          6615.1  ...       8100.575       9.225                 8100.0
76   1980   1          8266.6  ...       9931.275      -1.450                 9931.0
80   1981   1         10293.0  ...      12417.450       7.050                12417.0
84   1982   1         12390.4  ...      14321.650       8.400                14321.0
88   1983   1         14920.0  ...      17020.025      13.475                17020.0
92   1984   1         17255.3  ...      19647.825      10.750                19647.0
96   1985   1         19225.7  ...      22032.425       7.800                22032.0
100  1986   1         22516.7  ...      25746.475      11.225                25746.0
104  1987   1         26475.0  ...      30424.450      12.900                30424.0
108  1988   1         32844.3  ...      36498.700      12.100                36498.0
112  1989   1         37066.4  ...      41450.450       7.000                41450.0
116  1990   1         44060.8  ...      50139.075       9.900                50139.0
120  1991   1         53527.2  ...      60620.275      10.825                60620.0
124  1992   1         63005.5  ...      69385.175       6.300                69385.0
128  1993   1         70650.3  ...      78795.325       6.825                78795.0
132  1994   1         83453.5  ...      93123.350       9.275                93123.0
136  1995   1         98054.3  ...     109247.175       9.650               109247.0
140  1996   1        112294.5  ...     122712.725       7.900               122712.0
144  1997   1        122408.5  ...     135500.450       6.200               135500.0
148  1998   1        131111.0  ...     134303.850      -5.075               134303.0
152  1999   1        133692.3  ...     147863.250      11.375               147863.0
156  2000   1        152404.4  ...     162857.825       9.200               162857.0
160  2001   1        165662.3  ...     176705.325       4.850               176705.0
164  2002   1        182815.1  ...     196185.325       7.700               196185.0
168  2003   1        196663.6  ...     209341.275       3.150               209341.0
172  2004   1        213471.2  ...     227109.825       5.250               227109.0
176  2005   1        224035.8  ...     239361.950       4.300               239361.0
180  2006   1        236667.5  ...     251400.375       5.275               251400.0
184  2007   1        252586.3  ...     272415.050       5.775               272415.0
188  2008   1        271693.8  ...     288554.150       3.125               288554.0
192  2009   1        278108.8  ...     301336.950       0.775               301336.0
196  2010   1        307737.9  ...     330652.800       6.825               330652.0
200  2011   1        328096.0  ...     347234.300       3.725               347234.0
204  2012   1        344574.6  ...     360027.825       2.400               360027.0
208  2013   1        355384.7  ...     375204.800       3.150               375204.0
212  2014   1        373559.7  ...     390732.250       3.225               390732.0
216  2015   1        394273.0  ...     414505.100       2.775               414505.0
220  2016   1        413482.6  ...     435194.875       2.950               435194.0
224  2017   1        433027.3  ...     458924.525       3.150               458924.0
228  2018   1        449838.1  ...     474548.150       2.900               474548.0
232  2019   1        454891.0  ...     479759.950       2.050               479759.0
236  2020   1        458202.4  ...     478453.025      -0.300               478453.0

[60 rows x 7 columns]

### Requests

In [23]:
import requests
import pandas as pd

In [24]:
GDP_URL = 'https://www.index.go.kr/exceldown.do'

In [25]:
GDP_COOKIES = {
    'JSESSIONID': 'Glmk3jcQ6M0vFbDNJ4smM8noSD9dLZ6i74iD63fqDKaaMVwDJY0yeWsLvKFhVRZc.wasgams1_servlet_engine1',
    'chrCookie1621254278202': 'cookieValue',
    'idxCd_2736': '2736'
}

In [26]:
GDP_HEADERS = {
	'Connection': 'keep-alive',
	'Cache-Control': 'max-age=0',
	'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
	'sec-ch-ua-mobile': '?0',
	'Upgrade-Insecure-Requests': '1',
	'Origin': 'https://www.index.go.kr',
	'Content-Type': 'application/x-www-form-urlencoded',
	'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
	'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
	'Sec-Fetch-Site': 'same-origin',
	'Sec-Fetch-Mode': 'navigate',
	'Sec-Fetch-User': '?1',
	'Sec-Fetch-Dest': 'iframe',
	'Referer': 'https://www.index.go.kr/strata/jsp/showStblGams3.jsp?stts_cd=273601&idx_cd=2736&freq=Q&period=196001:202102',
	'Accept-Language': 'ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7'
}

In [27]:
GDP_DATA = {
	'datavalue': '1@span1@span@th@cell1@span1@span19601/4@th@cell1@span1@span19602/4@th@cell1@span1@span19603/4@th@cell1@span1@span19604/4@th@cell1@span1@span19611/4@th@cell1@span1@span19612/4@th@cell1@span1@span19613/4@th@cell1@span1@span19614/4@th@cell1@span1@span19621/4@th@cell1@span1@span19622/4@th@cell1@span1@span19623/4@th@cell1@span1@span19624/4@th@cell1@span1@span19631/4@th@cell1@span1@span19632/4@th@cell1@span1@span19633/4@th@cell1@span1@span19634/4@th@cell1@span1@span19641/4@th@cell1@span1@span19642/4@th@cell1@span1@span19643/4@th@cell1@span1@span19644/4@th@cell1@span1@span19651/4@th@cell1@span1@span19652/4@th@cell1@span1@span19653/4@th@cell1@span1@span19654/4@th@cell1@span1@span19661/4@th@cell1@span1@span19662/4@th@cell1@span1@span19663/4@th@cell1@span1@span19664/4@th@cell1@span1@span19671/4@th@cell1@span1@span19672/4@th@cell1@span1@span19673/4@th@cell1@span1@span19674/4@th@cell1@span1@span19681/4@th@cell1@span1@span19682/4@th@cell1@span1@span19683/4@th@cell1@span1@span19684/4@th@cell1@span1@span19691/4@th@cell1@span1@span19692/4@th@cell1@span1@span19693/4@th@cell1@span1@span19694/4@th@cell1@span1@span19701/4@th@cell1@span1@span19702/4@th@cell1@span1@span19703/4@th@cell1@span1@span19704/4@th@cell1@span1@span19711/4@th@cell1@span1@span19712/4@th@cell1@span1@span19713/4@th@cell1@span1@span19714/4@th@cell1@span1@span19721/4@th@cell1@span1@span19722/4@th@cell1@span1@span19723/4@th@cell1@span1@span19724/4@th@cell1@span1@span19731/4@th@cell1@span1@span19732/4@th@cell1@span1@span19733/4@th@cell1@span1@span19734/4@th@cell1@span1@span19741/4@th@cell1@span1@span19742/4@th@cell1@span1@span19743/4@th@cell1@span1@span19744/4@th@cell1@span1@span19751/4@th@cell1@span1@span19752/4@th@cell1@span1@span19753/4@th@cell1@span1@span19754/4@th@cell1@span1@span19761/4@th@cell1@span1@span19762/4@th@cell1@span1@span19763/4@th@cell1@span1@span19764/4@th@cell1@span1@span19771/4@th@cell1@span1@span19772/4@th@cell1@span1@span19773/4@th@cell1@span1@span19774/4@th@cell1@span1@span19781/4@th@cell1@span1@span19782/4@th@cell1@span1@span19783/4@th@cell1@span1@span19784/4@th@cell1@span1@span19791/4@th@cell1@span1@span19792/4@th@cell1@span1@span19793/4@th@cell1@span1@span19794/4@th@cell1@span1@span19801/4@th@cell1@span1@span19802/4@th@cell1@span1@span19803/4@th@cell1@span1@span19804/4@th@cell1@span1@span19811/4@th@cell1@span1@span19812/4@th@cell1@span1@span19813/4@th@cell1@span1@span19814/4@th@cell1@span1@span19821/4@th@cell1@span1@span19822/4@th@cell1@span1@span19823/4@th@cell1@span1@span19824/4@th@cell1@span1@span19831/4@th@cell1@span1@span19832/4@th@cell1@span1@span19833/4@th@cell1@span1@span19834/4@th@cell1@span1@span19841/4@th@cell1@span1@span19842/4@th@cell1@span1@span19843/4@th@cell1@span1@span19844/4@th@cell1@span1@span19851/4@th@cell1@span1@span19852/4@th@cell1@span1@span19853/4@th@cell1@span1@span19854/4@th@cell1@span1@span19861/4@th@cell1@span1@span19862/4@th@cell1@span1@span19863/4@th@cell1@span1@span19864/4@th@cell1@span1@span19871/4@th@cell1@span1@span19872/4@th@cell1@span1@span19873/4@th@cell1@span1@span19874/4@th@cell1@span1@span19881/4@th@cell1@span1@span19882/4@th@cell1@span1@span19883/4@th@cell1@span1@span19884/4@th@cell1@span1@span19891/4@th@cell1@span1@span19892/4@th@cell1@span1@span19893/4@th@cell1@span1@span19894/4@th@cell1@span1@span19901/4@th@cell1@span1@span19902/4@th@cell1@span1@span19903/4@th@cell1@span1@span19904/4@th@cell1@span1@span19911/4@th@cell1@span1@span19912/4@th@cell1@span1@span19913/4@th@cell1@span1@span19914/4@th@cell1@span1@span19921/4@th@cell1@span1@span19922/4@th@cell1@span1@span19923/4@th@cell1@span1@span19924/4@th@cell1@span1@span19931/4@th@cell1@span1@span19932/4@th@cell1@span1@span19933/4@th@cell1@span1@span19934/4@th@cell1@span1@span19941/4@th@cell1@span1@span19942/4@th@cell1@span1@span19943/4@th@cell1@span1@span19944/4@th@cell1@span1@span19951/4@th@cell1@span1@span19952/4@th@cell1@span1@span19953/4@th@cell1@span1@span19954/4@th@cell1@span1@span19961/4@th@cell1@span1@span19962/4@th@cell1@span1@span19963/4@th@cell1@span1@span19964/4@th@cell1@span1@span19971/4@th@cell1@span1@span19972/4@th@cell1@span1@span19973/4@th@cell1@span1@span19974/4@th@cell1@span1@span19981/4@th@cell1@span1@span19982/4@th@cell1@span1@span19983/4@th@cell1@span1@span19984/4@th@cell1@span1@span19991/4@th@cell1@span1@span19992/4@th@cell1@span1@span19993/4@th@cell1@span1@span19994/4@th@cell1@span1@span20001/4@th@cell1@span1@span20002/4@th@cell1@span1@span20003/4@th@cell1@span1@span20004/4@th@cell1@span1@span20011/4@th@cell1@span1@span20012/4@th@cell1@span1@span20013/4@th@cell1@span1@span20014/4@th@cell1@span1@span20021/4@th@cell1@span1@span20022/4@th@cell1@span1@span20023/4@th@cell1@span1@span20024/4@th@cell1@span1@span20031/4@th@cell1@span1@span20032/4@th@cell1@span1@span20033/4@th@cell1@span1@span20034/4@th@cell1@span1@span20041/4@th@cell1@span1@span20042/4@th@cell1@span1@span20043/4@th@cell1@span1@span20044/4@th@cell1@span1@span20051/4@th@cell1@span1@span20052/4@th@cell1@span1@span20053/4@th@cell1@span1@span20054/4@th@cell1@span1@span20061/4@th@cell1@span1@span20062/4@th@cell1@span1@span20063/4@th@cell1@span1@span20064/4@th@cell1@span1@span20071/4@th@cell1@span1@span20072/4@th@cell1@span1@span20073/4@th@cell1@span1@span20074/4@th@cell1@span1@span20081/4@th@cell1@span1@span20082/4@th@cell1@span1@span20083/4@th@cell1@span1@span20084/4@th@cell1@span1@span20091/4@th@cell1@span1@span20092/4@th@cell1@span1@span20093/4@th@cell1@span1@span20094/4@th@cell1@span1@span20101/4@th@cell1@span1@span20102/4@th@cell1@span1@span20103/4@th@cell1@span1@span20104/4@th@cell1@span1@span20111/4@th@cell1@span1@span20112/4@th@cell1@span1@span20113/4@th@cell1@span1@span20114/4@th@cell1@span1@span20121/4@th@cell1@span1@span20122/4@th@cell1@span1@span20123/4@th@cell1@span1@span20124/4@th@cell1@span1@span20131/4@th@cell1@span1@span20132/4@th@cell1@span1@span20133/4@th@cell1@span1@span20134/4@th@cell1@span1@span20141/4@th@cell1@span1@span20142/4@th@cell1@span1@span20143/4@th@cell1@span1@span20144/4@th@cell1@span1@span20151/4@th@cell1@span1@span20152/4@th@cell1@span1@span20153/4@th@cell1@span1@span20154/4@th@cell1@span1@span20161/4@th@cell1@span1@span20162/4@th@cell1@span1@span20163/4@th@cell1@span1@span20164/4@th@cell1@span1@span20171/4@th@cell1@span1@span20172/4@th@cell1@span1@span20173/4@th@cell1@span1@span20174/4@th@cell1@span1@span20181/4@th@cell1@span1@span20182/4@th@cell1@span1@span20183/4@th@cell1@span1@span20184/4@th@cell1@span1@span20191/4@th@cell1@span1@span20192/4@th@cell1@span1@span20193/4@th@cell1@span1@span20194/4@th@cell1@span1@span20201/4@th@cell1@span1@span20202/4@th@cell1@span1@span20203/4@th@cell1@span1@span20204/4@th@cell1@span1@span20211/4@th@cell1@span1@span20212/4@th@cell@row1@span1@span국내총생산(명목GDP)@th@cell1@span1@span49.1@td@cell1@span1@span68.0@td@cell1@span1@span61.0@td@cell1@span1@span71.8@td@cell1@span1@span62.0@td@cell1@span1@span83.2@td@cell1@span1@span70.6@td@cell1@span1@span85.9@td@cell1@span1@span72.7@td@cell1@span1@span99.4@td@cell1@span1@span84.8@td@cell1@span1@span109.0@td@cell1@span1@span97.6@td@cell1@span1@span135.0@td@cell1@span1@span124.2@td@cell1@span1@span161.7@td@cell1@span1@span128.5@td@cell1@span1@span198.2@td@cell1@span1@span180.2@td@cell1@span1@span232.7@td@cell1@span1@span162.2@td@cell1@span1@span227.8@td@cell1@span1@span201.3@td@cell1@span1@span240.0@td@cell1@span1@span198.1@td@cell1@span1@span294.8@td@cell1@span1@span271.1@td@cell1@span1@span301.9@td@cell1@span1@span244.8@td@cell1@span1@span353.9@td@cell1@span1@span338.5@td@cell1@span1@span376.6@td@cell1@span1@span330.9@td@cell1@span1@span463.6@td@cell1@span1@span435.0@td@cell1@span1@span462.9@td@cell1@span1@span395.9@td@cell1@span1@span568.3@td@cell1@span1@span594.1@td@cell1@span1@span653.1@td@cell1@span1@span536.9@td@cell1@span1@span714.2@td@cell1@span1@span727.5@td@cell1@span1@span818.0@td@cell1@span1@span674.1@td@cell1@span1@span918.3@td@cell1@span1@span881.3@td@cell1@span1@span964.4@td@cell1@span1@span804.7@td@cell1@span1@span1,125.8@td@cell1@span1@span1,100.2@td@cell1@span1@span1,237.0@td@cell1@span1@span1,039.8@td@cell1@span1@span1,414.2@td@cell1@span1@span1,449.2@td@cell1@span1@span1,624.2@td@cell1@span1@span1,545.6@td@cell1@span1@span2,024.8@td@cell1@span1@span1,987.4@td@cell1@span1@span2,347.2@td@cell1@span1@span2,007.6@td@cell1@span1@span2,766.0@td@cell1@span1@span2,666.3@td@cell1@span1@span3,103.7@td@cell1@span1@span2,806.7@td@cell1@span1@span3,820.4@td@cell1@span1@span3,704.3@td@cell1@span1@span4,141.4@td@cell1@span1@span3,569.8@td@cell1@span1@span4,675.0@td@cell1@span1@span4,770.1@td@cell1@span1@span5,593.2@td@cell1@span1@span4,813.0@td@cell1@span1@span6,327.1@td@cell1@span1@span6,549.6@td@cell1@span1@span7,464.7@td@cell1@span1@span6,615.1@td@cell1@span1@span8,219.9@td@cell1@span1@span8,364.5@td@cell1@span1@span9,202.8@td@cell1@span1@span8,266.6@td@cell1@span1@span10,020.7@td@cell1@span1@span10,342.3@td@cell1@span1@span11,095.5@td@cell1@span1@span10,293.0@td@cell1@span1@span12,496.2@td@cell1@span1@span12,950.0@td@cell1@span1@span13,930.6@td@cell1@span1@span12,390.4@td@cell1@span1@span14,369.1@td@cell1@span1@span14,768.4@td@cell1@span1@span15,758.7@td@cell1@span1@span14,920.0@td@cell1@span1@span16,816.9@td@cell1@span1@span17,844.9@td@cell1@span1@span18,498.3@td@cell1@span1@span17,255.3@td@cell1@span1@span19,441.0@td@cell1@span1@span20,760.8@td@cell1@span1@span21,134.2@td@cell1@span1@span19,225.7@td@cell1@span1@span21,604.7@td@cell1@span1@span23,186.6@td@cell1@span1@span24,112.7@td@cell1@span1@span22,516.7@td@cell1@span1@span25,054.2@td@cell1@span1@span27,045.1@td@cell1@span1@span28,369.9@td@cell1@span1@span26,475.0@td@cell1@span1@span29,808.6@td@cell1@span1@span31,447.9@td@cell1@span1@span33,966.3@td@cell1@span1@span32,844.3@td@cell1@span1@span35,040.9@td@cell1@span1@span37,510.9@td@cell1@span1@span40,598.7@td@cell1@span1@span37,066.4@td@cell1@span1@span39,973.7@td@cell1@span1@span42,208.8@td@cell1@span1@span46,552.9@td@cell1@span1@span44,060.8@td@cell1@span1@span48,660.9@td@cell1@span1@span52,433.0@td@cell1@span1@span55,401.6@td@cell1@span1@span53,527.2@td@cell1@span1@span59,330.8@td@cell1@span1@span62,525.4@td@cell1@span1@span67,097.7@td@cell1@span1@span63,005.5@td@cell1@span1@span69,226.4@td@cell1@span1@span70,880.4@td@cell1@span1@span74,428.4@td@cell1@span1@span70,650.3@td@cell1@span1@span78,308.1@td@cell1@span1@span80,911.1@td@cell1@span1@span85,311.8@td@cell1@span1@span83,453.5@td@cell1@span1@span91,513.3@td@cell1@span1@span95,615.3@td@cell1@span1@span101,911.3@td@cell1@span1@span98,054.3@td@cell1@span1@span108,417.9@td@cell1@span1@span113,779.6@td@cell1@span1@span116,736.9@td@cell1@span1@span112,294.5@td@cell1@span1@span121,161.5@td@cell1@span1@span126,073.8@td@cell1@span1@span131,321.1@td@cell1@span1@span122,408.5@td@cell1@span1@span133,583.6@td@cell1@span1@span139,134.8@td@cell1@span1@span146,874.9@td@cell1@span1@span131,111.0@td@cell1@span1@span131,834.6@td@cell1@span1@span134,676.5@td@cell1@span1@span139,593.3@td@cell1@span1@span133,692.3@td@cell1@span1@span143,533.4@td@cell1@span1@span152,776.0@td@cell1@span1@span161,451.3@td@cell1@span1@span152,404.4@td@cell1@span1@span160,404.4@td@cell1@span1@span166,224.9@td@cell1@span1@span172,397.6@td@cell1@span1@span165,662.3@td@cell1@span1@span176,302.9@td@cell1@span1@span179,613.6@td@cell1@span1@span185,242.5@td@cell1@span1@span182,815.1@td@cell1@span1@span195,025.5@td@cell1@span1@span197,296.0@td@cell1@span1@span209,604.7@td@cell1@span1@span196,663.6@td@cell1@span1@span205,785.3@td@cell1@span1@span209,454.4@td@cell1@span1@span225,461.8@td@cell1@span1@span213,471.2@td@cell1@span1@span225,589.8@td@cell1@span1@span229,235.5@td@cell1@span1@span240,142.8@td@cell1@span1@span224,035.8@td@cell1@span1@span235,823.7@td@cell1@span1@span242,709.8@td@cell1@span1@span254,878.5@td@cell1@span1@span236,667.5@td@cell1@span1@span246,819.2@td@cell1@span1@span255,259.1@td@cell1@span1@span266,855.7@td@cell1@span1@span252,586.3@td@cell1@span1@span268,345.3@td@cell1@span1@span275,865.8@td@cell1@span1@span292,862.8@td@cell1@span1@span271,693.8@td@cell1@span1@span289,566.5@td@cell1@span1@span295,242.9@td@cell1@span1@span297,713.4@td@cell1@span1@span278,108.8@td@cell1@span1@span297,889.5@td@cell1@span1@span309,041.3@td@cell1@span1@span320,308.2@td@cell1@span1@span307,737.9@td@cell1@span1@span329,481.0@td@cell1@span1@span334,833.6@td@cell1@span1@span350,558.7@td@cell1@span1@span328,096.0@td@cell1@span1@span343,678.8@td@cell1@span1@span349,987.0@td@cell1@span1@span367,175.4@td@cell1@span1@span344,574.6@td@cell1@span1@span358,275.7@td@cell1@span1@span361,834.3@td@cell1@span1@span375,426.7@td@cell1@span1@span355,384.7@td@cell1@span1@span373,096.5@td@cell1@span1@span379,887.2@td@cell1@span1@span392,450.8@td@cell1@span1@span373,559.7@td@cell1@span1@span388,566.9@td@cell1@span1@span393,425.4@td@cell1@span1@span407,377.0@td@cell1@span1@span394,273.0@td@cell1@span1@span411,386.8@td@cell1@span1@span420,790.8@td@cell1@span1@span431,569.8@td@cell1@span1@span413,482.6@td@cell1@span1@span434,462.9@td@cell1@span1@span439,421.6@td@cell1@span1@span453,412.4@td@cell1@span1@span433,027.3@td@cell1@span1@span454,141.7@td@cell1@span1@span473,436.2@td@cell1@span1@span475,092.9@td@cell1@span1@span449,838.1@td@cell1@span1@span473,018.3@td@cell1@span1@span485,535.7@td@cell1@span1@span489,800.5@td@cell1@span1@span454,891.0@td@cell1@span1@span479,907.0@td@cell1@span1@span487,177.0@td@cell1@span1@span497,064.8@td@cell1@span1@span458,202.4@td@cell1@span1@span472,328.1@td@cell1@span1@span491,181.5@td@cell1@span1@span492,100.1@td@cell1@span1@span501,248.1@td@cell1@span1@span-@td@cell@row1@span1@span경제성장률(실질GDP성장률)@th@cell1@span1@span-@td@cell1@span1@span-@td@cell1@span1@span-@td@cell1@span1@span-@td@cell1@span1@span6.3@td@cell1@span1@span7.2@td@cell1@span1@span4.8@td@cell1@span1@span9.0@td@cell1@span1@span6.3@td@cell1@span1@span-1.6@td@cell1@span1@span7.2@td@cell1@span1@span4.4@td@cell1@span1@span10.1@td@cell1@span1@span8.7@td@cell1@span1@span9.7@td@cell1@span1@span7.9@td@cell1@span1@span4.7@td@cell1@span1@span5.7@td@cell1@span1@span8.2@td@cell1@span1@span17.6@td@cell1@span1@span8.2@td@cell1@span1@span13.8@td@cell1@span1@span7.4@td@cell1@span1@span1.6@td@cell1@span1@span8.1@td@cell1@span1@span13.7@td@cell1@span1@span15.8@td@cell1@span1@span10.5@td@cell1@span1@span9.5@td@cell1@span1@span5.1@td@cell1@span1@span14.1@td@cell1@span1@span8.3@td@cell1@span1@span13.5@td@cell1@span1@span13.6@td@cell1@span1@span15.7@td@cell1@span1@span10.3@td@cell1@span1@span9.0@td@cell1@span1@span12.7@td@cell1@span1@span14.2@td@cell1@span1@span20.9@td@cell1@span1@span10.6@td@cell1@span1@span13.7@td@cell1@span1@span4.8@td@cell1@span1@span11.2@td@cell1@span1@span12.8@td@cell1@span1@span13.2@td@cell1@span1@span11.4@td@cell1@span1@span6.1@td@cell1@span1@span5.5@td@cell1@span1@span5.2@td@cell1@span1@span6.3@td@cell1@span1@span11.1@td@cell1@span1@span12.7@td@cell1@span1@span13.5@td@cell1@span1@span18.3@td@cell1@span1@span14.9@td@cell1@span1@span15.5@td@cell1@span1@span10.8@td@cell1@span1@span7.6@td@cell1@span1@span5.8@td@cell1@span1@span2.2@td@cell1@span1@span6.6@td@cell1@span1@span8.2@td@cell1@span1@span13.0@td@cell1@span1@span12.3@td@cell1@span1@span14.6@td@cell1@span1@span13.6@td@cell1@span1@span12.4@td@cell1@span1@span9.2@td@cell1@span1@span8.8@td@cell1@span1@span13.5@td@cell1@span1@span16.5@td@cell1@span1@span15.1@td@cell1@span1@span13.1@td@cell1@span1@span9.8@td@cell1@span1@span7.5@td@cell1@span1@span14.6@td@cell1@span1@span11.6@td@cell1@span1@span7.8@td@cell1@span1@span2.9@td@cell1@span1@span0.2@td@cell1@span1@span-3.5@td@cell1@span1@span2.3@td@cell1@span1@span-4.8@td@cell1@span1@span3.8@td@cell1@span1@span3.9@td@cell1@span1@span7.9@td@cell1@span1@span12.6@td@cell1@span1@span9.0@td@cell1@span1@span8.7@td@cell1@span1@span8.2@td@cell1@span1@span7.7@td@cell1@span1@span13.7@td@cell1@span1@span13.4@td@cell1@span1@span16.1@td@cell1@span1@span10.7@td@cell1@span1@span13.8@td@cell1@span1@span12.2@td@cell1@span1@span9.5@td@cell1@span1@span7.5@td@cell1@span1@span7.5@td@cell1@span1@span6.7@td@cell1@span1@span7.3@td@cell1@span1@span9.7@td@cell1@span1@span9.1@td@cell1@span1@span10.2@td@cell1@span1@span13.9@td@cell1@span1@span11.7@td@cell1@span1@span15.0@td@cell1@span1@span15.2@td@cell1@span1@span10.8@td@cell1@span1@span10.6@td@cell1@span1@span16.5@td@cell1@span1@span8.4@td@cell1@span1@span10.6@td@cell1@span1@span12.9@td@cell1@span1@span5.0@td@cell1@span1@span7.8@td@cell1@span1@span6.9@td@cell1@span1@span8.3@td@cell1@span1@span10.0@td@cell1@span1@span10.9@td@cell1@span1@span10.5@td@cell1@span1@span8.2@td@cell1@span1@span11.4@td@cell1@span1@span11.8@td@cell1@span1@span9.8@td@cell1@span1@span10.3@td@cell1@span1@span8.6@td@cell1@span1@span7.7@td@cell1@span1@span4.9@td@cell1@span1@span4.0@td@cell1@span1@span5.0@td@cell1@span1@span6.5@td@cell1@span1@span7.9@td@cell1@span1@span7.9@td@cell1@span1@span9.7@td@cell1@span1@span8.6@td@cell1@span1@span8.4@td@cell1@span1@span10.4@td@cell1@span1@span9.6@td@cell1@span1@span10.0@td@cell1@span1@span10.8@td@cell1@span1@span8.2@td@cell1@span1@span8.1@td@cell1@span1@span8.1@td@cell1@span1@span7.9@td@cell1@span1@span7.5@td@cell1@span1@span6.0@td@cell1@span1@span7.6@td@cell1@span1@span6.9@td@cell1@span1@span4.3@td@cell1@span1@span-2.9@td@cell1@span1@span-7.2@td@cell1@span1@span-6.4@td@cell1@span1@span-3.8@td@cell1@span1@span7.0@td@cell1@span1@span12.2@td@cell1@span1@span12.8@td@cell1@span1@span13.5@td@cell1@span1@span12.7@td@cell1@span1@span9.1@td@cell1@span1@span9.1@td@cell1@span1@span5.9@td@cell1@span1@span5.1@td@cell1@span1@span4.9@td@cell1@span1@span3.5@td@cell1@span1@span5.9@td@cell1@span1@span7.2@td@cell1@span1@span7.6@td@cell1@span1@span8.2@td@cell1@span1@span7.8@td@cell1@span1@span4.2@td@cell1@span1@span2.3@td@cell1@span1@span2.1@td@cell1@span1@span4.0@td@cell1@span1@span5.8@td@cell1@span1@span6.7@td@cell1@span1@span5.2@td@cell1@span1@span3.3@td@cell1@span1@span3.0@td@cell1@span1@span3.9@td@cell1@span1@span5.0@td@cell1@span1@span5.3@td@cell1@span1@span6.4@td@cell1@span1@span4.8@td@cell1@span1@span5.1@td@cell1@span1@span4.8@td@cell1@span1@span4.9@td@cell1@span1@span5.9@td@cell1@span1@span5.5@td@cell1@span1@span6.8@td@cell1@span1@span5.8@td@cell1@span1@span4.4@td@cell1@span1@span4.0@td@cell1@span1@span-1.7@td@cell1@span1@span-1.8@td@cell1@span1@span-1.2@td@cell1@span1@span0.9@td@cell1@span1@span5.2@td@cell1@span1@span7.3@td@cell1@span1@span7.9@td@cell1@span1@span5.8@td@cell1@span1@span6.3@td@cell1@span1@span5.4@td@cell1@span1@span3.8@td@cell1@span1@span3.1@td@cell1@span1@span2.6@td@cell1@span1@span2.4@td@cell1@span1@span2.4@td@cell1@span1@span2.3@td@cell1@span1@span2.5@td@cell1@span1@span2.3@td@cell1@span1@span2.9@td@cell1@span1@span3.5@td@cell1@span1@span3.9@td@cell1@span1@span3.8@td@cell1@span1@span3.4@td@cell1@span1@span3.1@td@cell1@span1@span2.6@td@cell1@span1@span2.4@td@cell1@span1@span2.0@td@cell1@span1@span3.3@td@cell1@span1@span3.4@td@cell1@span1@span2.8@td@cell1@span1@span3.6@td@cell1@span1@span2.8@td@cell1@span1@span2.6@td@cell1@span1@span3.1@td@cell1@span1@span2.7@td@cell1@span1@span3.9@td@cell1@span1@span2.9@td@cell1@span1@span3.0@td@cell1@span1@span3.1@td@cell1@span1@span2.4@td@cell1@span1@span3.1@td@cell1@span1@span1.8@td@cell1@span1@span2.1@td@cell1@span1@span2.0@td@cell1@span1@span2.3@td@cell1@span1@span-1.3@td@cell1@span1@span-3.2@td@cell1@span1@span2.2@td@cell1@span1@span1.1@td@cell1@span1@span1.7@td@cell1@span1@span0.7@td@cell@row',
	'idxcd': '2736',
	'sttscd': '273601'
}

In [28]:
response = requests.post(GDP_URL, headers=GDP_HEADERS, cookies=GDP_COOKIES, data=GDP_DATA)

In [29]:
with open("/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.xls", 'wb') as fd:
	for chunk in response.iter_content(chunk_size=1024):
		fd.write(chunk)
df = pd.read_excel("/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.xls", index_col=0)

In [30]:
df.head()

                국내총생산 및 경제성장률 Unnamed: 2  ... Unnamed: 245 Unnamed: 246
통계표명:                                     ...
단위:              십억원, 전년동기비 %        NaN  ...          NaN          NaN
NaN                   19601/4    19602/4  ...      20211/4      20212/4
국내총생산(명목GDP)             49.1       68.0  ...    501,248.1            -
경제성장률(실질GDP성장률)             -          -  ...          1.7          0.7
출처:                한국은행「국민소득」        NaN  ...          NaN          NaN

[5 rows x 246 columns]

In [31]:
df.T.to_csv("/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.csv", sep='|', na_rep='NaN', index=False)

In [32]:
df.T.head()

통계표명:                   단위:  ...                                                NaN
국내총생산 및 경제성장률  십억원, 전년동기비 %  ...  * 실질GDP, 실질성장률은 발표시기(한국은행, GDP속보치 발표)와 명목GDP, ...
Unnamed: 2              NaN  ...                                                NaN
Unnamed: 3              NaN  ...                                                NaN
Unnamed: 4              NaN  ...                                                NaN
Unnamed: 5              NaN  ...                                                NaN

[5 rows x 7 columns]

In [33]:
# 쓸데 없는 값들을 제거하고 정확하게 필드를 인식하게 하기위해 아래 전처리를 진행한다.
f = open("/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.csv", 'rt', encoding='UTF8')
lines = f.readlines()
lines = lines[2:]
f.close()

In [34]:
lines[10]

'NaN|19624/4|109.0|4.4|NaN|NaN|NaN\n'

In [35]:
print(lines[10].split('|')[1][0:4],': year')
print(lines[10].split('|')[1][4],': quarter')
print(lines[10].split('|')[2],': Nominal_GDP')
print(lines[10].split('|')[3],': Real_GDP')

1962 : year
4 : quarter
109.0 : Nominal_GDP
4.4 : Real_GDP

In [36]:
f = open("/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.csv", 'wt', encoding='UTF8')
f.write('year|quarter|Nominal_GDP|Real_GDP\n')
for line in lines:
	line_split = line.split('|')
	year = line_split[1][0:4]
	quarter = line_split[1][4]
	line = year + '|' + quarter + '|' + line_split[2] + '|' + line_split[3] + '\n'
	f.write(line)
f.close()

In [37]:
gdp = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.csv', sep='|', encoding='utf-8', low_memory=False)
# 중간에 - 값이 존재하는데 해당 값은 아직 확인이 되지 않은 값이다. 그래서 아래와 같이 필터링 했다.
gdp = gdp[(gdp['year'] >= 1961)&(gdp['year'] != 2021)]

In [38]:
gdp.head()

   year  quarter Nominal_GDP Real_GDP
3  1961        1        62.0      6.3
4  1961        2        83.2      7.2
5  1961        3        70.6      4.8
6  1961        4        85.9      9.0
7  1962        1        72.7      6.3

In [39]:
gdp['Nominal_GDP'] = gdp.Nominal_GDP.apply(lambda x: x.replace(',', ''))
gdp = gdp.astype({
    'Nominal_GDP': float,
    'Real_GDP': float
})
right = pd.DataFrame(gdp.groupby(['year'])['Nominal_GDP'].mean()).reset_index()
gdp_pre = pd.merge(gdp, right, how='left', left_on=['year'], right_on=['year'], suffixes=['_분기', '_년'])
right = pd.DataFrame(gdp.groupby(['year'])['Real_GDP'].mean()).reset_index()
gdp_pre = pd.merge(gdp_pre, right, how='left', left_on=['year'], right_on=['year'], suffixes=['_분기', '_년'])
gdp_pre = gdp_pre.rename(columns={
    'year': '년',
    'quarter': '분기'
})

In [40]:
gdp_pre.to_csv("/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/GDP.csv", sep='|', na_rep='NaN', index=False)

In [41]:
gdp_pre.head()

      년  분기  Nominal_GDP_분기  Real_GDP_분기  Nominal_GDP_년  Real_GDP_년
0  1961   1            62.0          6.3         75.425       6.825
1  1961   2            83.2          7.2         75.425       6.825
2  1961   3            70.6          4.8         75.425       6.825
3  1961   4            85.9          9.0         75.425       6.825
4  1962   1            72.7          6.3         91.475       4.075

### Beautifulsoup4

In [42]:
import requests
import pandas as pd
import bs4

In [43]:
def df_for_request(rows):
	# rows : <class 'bs4.element.ResultSet'>
	row_list = []
	name_list = []
	column_list = []
	rows_len = len(rows)
	for i in range(0, rows_len):
		columns = rows[i].find_all()
		columns_len = len(columns)
		for j in range(0, columns_len):
			if i == 0:
				#.name으로 html의 <"값">을 찾아온다.
				name_list.append(columns[j].name)
			eachColumn = columns[j].text
			column_list.append(eachColumn)
		row_list.append(column_list)
		column_list = []
	df = pd.DataFrame(row_list, columns=name_list)
	return df

In [44]:
def request_api(tx_columns, url, service_key, code, date):
	df = pd.DataFrame(columns=tx_columns)
	payload = "serviceKey=" + service_key + "&" \
		+ "LAWD_CD=" + code + "&" \
		+ "DEAL_YMD=" + date
	res = requests.get(url + payload).text
	return res

In [45]:
tx_columns = ['거래금액', '건축년도', '년', '법정동', '아파트', '월', '일', '전용면적', '지번', '지역코드', '층', '해제사유발생일', '해제여부']

In [46]:
url = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?"

In [47]:
sk = open('/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/ServiceKey.txt')
service_key = sk.readlines()[0]

In [48]:
csv = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Edu/Sample_Files/code.csv', delimiter="\t")
csv["code"] = csv.법정동코드.apply(lambda x: str(x)[0:5])
codes = list(set(csv.code.to_list()))

In [49]:
date_list = pd.date_range(start="2011-12-01", end="2011-12-01")
date_list = list(set(date_list.format(formatter=lambda x: x.strftime("%Y%m"))))

In [50]:
print(codes[0], date_list[0])

47750 201112

In [51]:
res = request_api(tx_columns, url, service_key, '11110', '201512')

In [52]:
xmlobj = bs4.BeautifulSoup(res, 'lxml-xml')

In [53]:
print(xmlobj)

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><거래금액>    82,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 사직동</법정동><아파트>광화문풍림스페이스본(101동~105동)</아파트><월>12</월><일>10</일><전용면적>94.51</전용면적><중개사소재지> </중개사소재지><지번>9</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    60,000</거래금액><거래유형> </거래유형><건축년도>1981</건축년도><년>2015</년><법정동> 당주동</법정동><아파트>롯데미도파광화문빌딩</아파트><월>12</월><일>22</일><전용면적>149.95</전용면적><중개사소재지> </중개사소재지><지번>145</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   130,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>킹스매너</아파트><월>12</월><일>8</일><전용면적>194.43</전용면적><중개사소재지> </중개사소재지><지번>110-15</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   105,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁의아침2단지</아파트><월>12</월><일>14</일><전용면적>124.17</전용면적><중개사소재지> </중개사소재지><지번>71</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   120,000</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 내수동</법정동><아파트>경희궁파크팰리스</아파트><월>12</월><일>24</일><전용면적>146.33</전용면적><중개사소재지> </중개사소재지><지번>95</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>17</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    17,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 연건동</법정동><아파트>이화에수풀</아파트><월>12</월><일>18</일><전용면적>16.98</전용면적><중개사소재지> </중개사소재지><지번>195-10</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    57,000</거래금액><거래유형> </거래유형><건축년도>2006</건축년도><년>2015</년><법정동> 명륜1가</법정동><아파트>렉스빌</아파트><월>12</월><일>29</일><전용면적>106.98</전용면적><중개사소재지> </중개사소재지><지번>19</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>1</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>18</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>10</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    49,800</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남1</아파트><월>12</월><일>19</일><전용면적>84.8</전용면적><중개사소재지> </중개사소재지><지번>4</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 명륜2가</법정동><아파트>아남3</아파트><월>12</월><일>19</일><전용면적>61.13</전용면적><중개사소재지> </중개사소재지><지번>237</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    41,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>2</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    19,500</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>3</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,900</거래금액><거래유형> </거래유형><건축년도>2003</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신이수</아파트><월>12</월><일>3</일><전용면적>68.06</전용면적><중개사소재지> </중개사소재지><지번>23-816</지번><지역코드>11110</지역코드><층>8</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    20,800</거래금액><거래유형> </거래유형><건축년도>1966</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>동대문</아파트><월>12</월><일>7</일><전용면적>28.8</전용면적><중개사소재지> </중개사소재지><지번>328-17</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,200</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>7</일><전용면적>64.66</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>10</일><전용면적>59.95</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,950</거래금액><거래유형> </거래유형><건축년도>1993</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>12</월><일>11</일><전용면적>115.53</전용면적><중개사소재지> </중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    34,500</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>12</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,000</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>14</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,800</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>22</일><전용면적>106.62</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    37,300</거래금액><거래유형> </거래유형><건축년도>1992</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>창신쌍용1</아파트><월>12</월><일>23</일><전용면적>79.87</전용면적><중개사소재지> </중개사소재지><지번>702</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    50,000</거래금액><거래유형> </거래유형><건축년도>1999</건축년도><년>2015</년><법정동> 창신동</법정동><아파트>두산</아파트><월>12</월><일>24</일><전용면적>84.9</전용면적><중개사소재지> </중개사소재지><지번>232</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    12,300</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로아인스빌</아파트><월>12</월><일>2</일><전용면적>12.15</전용면적><중개사소재지> </중개사소재지><지번>1392-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,000</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>3</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>19</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    53,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>5</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>5</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    13,000</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>12</월><일>8</일><전용면적>15.09</전용면적><중개사소재지> </중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,500</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>8</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    27,000</거래금액><거래유형> </거래유형><건축년도>1997</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>동문(비동,씨동)(494-0)</아파트><월>12</월><일>9</일><전용면적>59.94</전용면적><중개사소재지> </중개사소재지><지번>494</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,900</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>14</일><전용면적>59.9426</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    11,900</거래금액><거래유형> </거래유형><건축년도>2014</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>숭인한양LEEPS</아파트><월>12</월><일>14</일><전용면적>12.78</전용면적><중개사소재지> </중개사소재지><지번>1421-2</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,500</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>15.76</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,000</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>익성씨티하임</아파트><월>12</월><일>15</일><전용면적>14.48</전용면적><중개사소재지> </중개사소재지><지번>1392</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    42,500</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>19</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,700</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>22</일><전용면적>59.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,300</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>12</월><일>26</일><전용면적>84.92</전용면적><중개사소재지> </중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    10,800</거래금액><거래유형> </거래유형><건축년도>2013</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로유케이201</아파트><월>12</월><일>31</일><전용면적>12.01</전용면적><중개사소재지> </중개사소재지><지번>201-11</지번><지역코드>11110</지역코드><층>7</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    52,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>12</월><일>31</일><전용면적>84.9478</전용면적><중개사소재지> </중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    44,600</거래금액><거래유형> </거래유형><건축년도>1995</건축년도><년>2015</년><법정동> 교북동</법정동><아파트>동아</아파트><월>12</월><일>7</일><전용면적>84.28</전용면적><중개사소재지> </중개사소재지><지번>101</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   115,000</거래금액><거래유형> </거래유형><건축년도>2004</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>벽산블루밍평창힐스</아파트><월>12</월><일>2</일><전용면적>210.53</전용면적><중개사소재지> </중개사소재지><지번>45</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>   164,500</거래금액><거래유형> </거래유형><건축년도>2009</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>12</월><일>3</일><전용면적>219.775</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    31,500</거래금액><거래유형> </거래유형><건축년도>1998</건축년도><년>2015</년><법정동> 평창동</법정동><아파트>삼성</아파트><월>12</월><일>6</일><전용면적>59.97</전용면적><중개사소재지> </중개사소재지><지번>596</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    39,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>12</일><전용면적>60</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,490</거래금액><거래유형> </거래유형><건축년도>2000</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>현대</아파트><월>12</월><일>15</일><전용면적>114.9</전용면적><중개사소재지> </중개사소재지><지번>82</지번><지역코드>11110</지역코드><층>6</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    62,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>16</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    63,400</거래금액><거래유형> </거래유형><건축년도>2015</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산2차아이파크</아파트><월>12</월><일>22</일><전용면적>84.0284</전용면적><중개사소재지> </중개사소재지><지번>88</지번><지역코드>11110</지역코드><층>10</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>    61,000</거래금액><거래유형> </거래유형><건축년도>2008</건축년도><년>2015</년><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>12</월><일>25</일><전용면적>84.858</전용면적><중개사소재지> </중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>49</totalCount></body></response>

In [54]:
rows = xmlobj.findAll('item')

In [55]:
rows[0].find_all()

[<거래금액>    82,500</거래금액>,
 <거래유형> </거래유형>,
 <건축년도>2008</건축년도>,
 <년>2015</년>,
 <법정동> 사직동</법정동>,
 <아파트>광화문풍림스페이스본(101동~105동)</아파트>,
 <월>12</월>,
 <일>10</일>,
 <전용면적>94.51</전용면적>,
 <중개사소재지> </중개사소재지>,
 <지번>9</지번>,
 <지역코드>11110</지역코드>,
 <층>11</층>,
 <해제사유발생일> </해제사유발생일>,
 <해제여부> </해제여부>]

In [56]:
df = df_for_request(rows)

In [57]:
df.head()

         거래금액 거래유형  건축년도     년   법정동  ...      지번   지역코드   층 해제사유발생일 해제여부
0      82,500       2008  2015   사직동  ...       9  11110  11
1      60,000       1981  2015   당주동  ...     145  11110   8
2     130,000       2004  2015   내수동  ...  110-15  11110   6
3     105,000       2004  2015   내수동  ...      71  11110   8
4     120,000       2003  2015   내수동  ...      95  11110   4

[5 rows x 15 columns]